### ISSUE TITLE
error when import in other (not main) module

### ISSUE THREAD

**Issue by Malkolm063** [bjsawyer/mat-file-upload#1]
If i need to use component in other modules:
if i import MatFileUploadModule in my lazyloaded module i see this error
> ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
> Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

but if i import MatFileUploadModule in AppModule (main module) so this

> ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'showUploadButton' since it isn't a known property of 'mat-file-upload'. 
> 1. If 'mat-file-upload' is an Angular component and it has 'showUploadButton' input, then verify that it is part of this module.
> 2. If 'mat-file-upload' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

angular cli  7.3.0
Material 7.3.1

**Comment by diegochavz** [comment]
I have the same error :(

**Comment by jeetendra-choudhary** [comment]
I am also facing the same error.

**Comment by FranciscoGregorio** [comment]
`ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

Same here.
I will look into it.


I am using v8

 ```
"dependencies": {
    "@angular/animations": "^8.0.2",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "^8.0.2",
    "@angular/compiler": "^8.0.2",
    "@angular/core": "^8.0.2",
    "@angular/forms": "^8.0.2",
    "@angular/platform-browser": "^8.0.2",
    "@angular/platform-browser-dynamic": "^8.0.2",
    "@angular/platform-server": "^8.0.2",
    "@angular/router": "^8.0.2",
...
}
```

**Comment by bjsawyer** [comment]
This should be resolved by https://github.com/bjsawyer/mat-file-upload/commit/0b37e3ca8b7309f68243360f4a4979e837d36757.
