### ISSUE TITLE
"x" button displaying incorrectly

### ISSUE THREAD

**Issue by ZedTT** [bjsawyer/mat-file-upload#14]
![image](https://user-images.githubusercontent.com/47646286/82080536-9a3be280-9699-11ea-8fa5-09c4684ce940.png)

When no file has been uploaded, there is an "invisible" button that is still clickable and displays in the wrong position which can interfere with other styling on the page. The button can be seen by mousing over it or clicking it. 

Because of the positioning of this button, the upload button moves down when no file is selected, and up when a file is selected.

**Comment by bjsawyer** [comment]
Fixed in ad8a9da68aff5d4ccc77b05df0a988c44a0d489d
