### ISSUE TITLE
Not able to install the package. I used the command npm i mat-file-upload but then its not installing 

### ISSUE THREAD

**Issue by abhijit5721** [bjsawyer/mat-file-upload#17]

**Comment by abhijit5721** [comment]
ERROR in apps/qtair-tender-ui/src/app/tender/components/upload/upload.component.html:19:1 - error NG8001: 'mat-file-upload' is not a known element:
    1. If 'mat-file-upload' is an Angular component, then verify that it is part of this module.
    2. If 'mat-file-upload' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    19 <mat-file-upload></mat-file-upload>
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      apps/qtair-tender-ui/src/app/tender/components/upload/upload.component.ts:10:16
        10   templateUrl: './upload.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component UploadComponent.

**Comment by bjsawyer** [comment]
Have you imported the library into your AppModule?

**Comment by abhijit5721** [comment]
Yeah i have imported the library in AppModule and then it says its not angular module.
