### ISSUE TITLE
Scrollable item list.

### ISSUE THREAD

**Issue by Dav-Git** [bjsawyer/mat-file-upload#22]
Hello, I am using Mat-File-Upload in a project in which I need to upload a large number of files at a single time. Therefor, scrolling through the massive list of FileNames to get to the Download button is quite tideous so I thought to use a DIV and some CSS to save me from the pain.

However, it appears the ``mat-file-upload-queue`` processes the button presses for "Upload all" and the "x" by looking at it's children. My code using the DIV doesn't work. I also tried styling ``mat-file-upload-queue`` with an ``size: 50%; overflow: auto;`` already but that didn't give me the desired result.

Is there another approach I should be taking or can styling support be added in a way that would allow me to apply custom styles.

Thank you for your help in advance.

My HTML to clarify how I wanted to style the element:
```html
<mat-file-upload-queue #fileUploadQueue [fileAlias]="'file'" [httpUrl]="'http://localhost:1234'" style="height: 100%; overflow:auto;"\>
     <div style="overflow: auto; height: 90%">
           <mat-file-upload [file]="file" [id]="i" *ngFor="let file of fileUploadQueue.files; let i = index">
           </mat-file-upload>
     </div>
</mat-file-upload-queue>
```

**Comment by bjsawyer** [comment]
Hi @Dav-Git, sorry for the delayed response. This is something I haven't yet looked into but will take some time to investigate. Have you had any luck getting it to work since opening the issue?

**Comment by Dav-Git** [comment]
Hey, I have since switched to a different solution due to changes in my project. I still think this would be a nice addition.
