### ISSUE TITLE
Some problem in my project

### ISSUE THREAD

**Issue by antonello80pili** [bjsawyer/mat-file-upload#23]
Error: Failed to compile entry-point angular-material-fileupload (es2015 as esm2015) due to compilation errors:
node_modules/angular-material-fileupload/fesm2015/angular-material-fileupload.js:596:26 - error NG1010: Value at position 0 in the NgModule.imports of MatFileUploadModule is not a reference
  Value could not be determined statically.

596                 imports: [
                             ~
597                     MatProgressBarModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
602                     CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
603                 ],
    ~~~~~~~~~~~~~~~~~

  node_modules/angular-material-fileupload/fesm2015/angular-material-fileupload.js:597:21
    597                     MatProgressBarModule,
                            ~~~~~~~~~~~~~~~~~~~~
    Unknown reference.

**Comment by bjsawyer** [comment]
Hi @antonello80pili. Which version of Angular are you using?

**Comment by Nyasak** [comment]
Experienced same issue and i am using Angular 11
