### ISSUE TITLE
Angular 11.1.1 ASSERTION ERROR

### ISSUE THREAD

**Issue by arumlv** [bjsawyer/mat-file-upload#25]
Angular version 11.1.1
dev mode (run with ng serve)
Error: ASSERTION ERROR: Expecting flags [Expected=> number === boolean <=Actual]
    at throwError (core.js:210)
    at assertNumber (core.js:141)
    at ɵɵviewQuery (core.js:26497)
    at MatFileUploadComponent_Query (mat-file-upload.js:100)

call function ɵɵviewQuery(_c0, true);

**Comment by milkov85** [comment]
We are experiencing the same issue with `Angular CLI: 11.1.2` in **_dev mode_**, but when we build in `--prod` the issue is gone. After some testing we found that adding option `"optimization": true`  in `angular.json` for `configuration: dev`is resolving the issue, but is making the building/running very slow so it would be nice if the issue is fixed.

**Comment by bjsawyer** [comment]
Thanks for the feedback @arumlv and @milkov85. I have just updated the library to Angular v11.1.2 and published to npm. Please try pullng `mat-file-upload@latest` and see if that resolves the issues you're seeing.

**Comment by arumlv** [comment]
Big Thanks!
resolved

**Comment by milkov85** [comment]
@bjsawyer Quick reaction, thanks

**Comment by Edo2610** [comment]
Sorry for questions, @milkov85 with ( `"optimization": true in angular.json` for `configuration: dev` )  do you mean
`...
"architect": {
    ... ,
    "serve": {
        "configurations": {
            ... ,
            "dev": {
                "optimization": true
            }
        }
    }
}`

??

**Comment by milkov85** [comment]
> Sorry for questions, @milkov85 with ( `"optimization": true in angular.json` for `configuration: dev` ) do you mean
> `... "architect": { ... , "serve": { "configurations": { ... , "dev": { "optimization": true } } } }`
> 
> ??

Yep, this is it
