### ISSUE TITLE
More customizable text

### ISSUE THREAD

**Issue by AllTerrainDeveloper** [bjsawyer/mat-file-upload#3]
I've discovered this component among any other out there, and this seems for me the nicest one. There is just one thing that might be improved. Could you please add labels for the rest of the texts? Like 'Select files(s)' and 'Upload'

Thank you!

**Comment by bjsawyer** [comment]
Thanks @AllTerrainDeveloper! When you say "labels", do you mean allowing users to customize the text displayed (rather than forcing them to use `Select file(s)` and `Upload`?

**Comment by AllTerrainDeveloper** [comment]
Yes, that's the point.

Thank you

**Comment by bjsawyer** [comment]
Closed in version 1.1.1 💯
