### ISSUE TITLE
Compilation errors after update to Angular v12

### ISSUE THREAD

**Issue by nasik87** [bjsawyer/mat-file-upload#35]
Hello guys,
We just updated our project to the latest Angular cli version 12.
Unfortunatelly after a successfull compilation we have the following errors  in the terminal:
![image](https://user-images.githubusercontent.com/10865698/119654100-c2bff600-be30-11eb-9ab7-b2fed9dc3f62.png)

The error appears both on dev live server and on build.

**Comment by martyganz** [comment]
Published a beta version of my PR #38 here: https://www.npmjs.com/package/@martyganz/mat-file-upload - if @bjsawyer replies in the meantime he can publish an actual version in this repository.

**Comment by nasik87** [comment]
It's working as expected. Thanks!! :+1:

**Comment by bjsawyer** [comment]
Apologies for the long delay - I am getting back to supporting this repo and have just published an [Angular 12 version here](https://www.npmjs.com/package/mat-file-upload/v/12.0.0). I will publish corresponding versions all the way up through the latest NG version as well.
