### ISSUE TITLE
Multiple properties not functioning at all

### ISSUE THREAD

**Issue by dominic1298** [bjsawyer/mat-file-upload#8]
I'm running Angular 7 and using mat-file-upload inside a material stepper.

I have found that the following properties are not valid, and output the error message:
`Can't bind to 'acceptedTypes' [or any of the other properties listed below] since it isn't a known property of 'mat-file-upload'`.

These properties include:

- [acceptedTypes]
- [selectButtonText]
- [uploadButtonText]
- [customSvgIcon]

My code is as follows:

```
      <mat-file-upload
        (uploadClicked)="onUploadClicked($event, 'collateral')"
        [allowMultipleFiles]="true"
        [acceptedTypes]="'.pdf'"
        [labelText]="'Select collateral files to upload. Please ensure they are named appropriately.'"
        [showUploadButton]="true">
      </mat-file-upload>
```

**Comment by bjsawyer** [comment]
Hi @dominic1298 - are you able to provide a StackBlitz reproducing the error message?
